# Import library yang diperlukan

In [ ]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix,
    f1_score, accuracy_score, ConfusionMatrixDisplay
)

# Upload dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('DATA (1).csv')

Saving DATA (1).csv to DATA (1).csv

# Data Understanding

## Melihat jumlah row, kolom dan 5 data pertama

In [ ]:
print(df.shape)
df.head()

(145, 33)

,STUDENT ID,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1

## Statistik Deskriptif awal

In [ ]:
df.describe()

,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,COURSE ID,GRADE
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,...,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000
mean,1.620690,1.600000,1.944828,3.572414,1.662069,1.600000,1.579310,1.627586,1.620690,1.731034,...,1.337931,1.165517,2.544828,2.055172,2.393103,1.806897,3.124138,2.724138,4.131034,3.227586
std,0.613154,0.491596,0.537216,0.805750,0.474644,0.491596,0.495381,1.020245,1.061112,0.783999,...,0.614870,0.408483,0.564940,0.674736,0.604343,0.810492,1.301083,0.916536,3.260145,2.197678
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,1.000000,1.000000
50%,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,3.000000
75%,2.000000,2.000000,2.000000,4.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,1.000000,3.000000,3.000000,3.000000,2.000000,4.000000,3.000000,7.000000,5.000000
max,3.000000,2.000000,3.000000,5.000000,2.000000,2.000000,2.000000,5.000000,4.000000,4.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,5.000000,4.000000,9.000000,7.000000

## Pengecekan jumlah class

In [ ]:
kelas = df.iloc[:, -1].unique()
jumlah_kelas = df.iloc[:, -1].nunique()
print(kelas)
print("Jumlah kelas:", jumlah_kelas)

[1 2 5 0 3 4 7 6]
Jumlah kelas: 8

## Pengecekan duplikat data

In [ ]:
df.duplicated().sum()

np.int64(0)

## Pengecekan data null/kosong

In [ ]:
df.isnull().sum()

STUDENT ID    0
1             0
2             0
3             0
4             0
5             0
6             0
7             0
8             0
9             0
10            0
11            0
12            0
13            0
14            0
15            0
16            0
17            0
18            0
19            0
20            0
21            0
22            0
23            0
24            0
25            0
26            0
27            0
28            0
29            0
30            0
COURSE ID     0
GRADE         0
dtype: int64

In [ ]:
print("Missing values:\n", df.isnull().sum().sum())
print("\nDistribusi GRADE:\n", df['GRADE'].value_counts().sort_index())

Missing values:
 0

Distribusi GRADE:
 GRADE
0     8
1    35
2    24
3    21
4    10
5    17
6    13
7    17
Name: count, dtype: int64

# Data prepocessing

## Pisahkan kolom fitur dan class

In [ ]:
X = df.drop(columns=['STUDENT ID', 'GRADE'])
y = df['GRADE']

print("Jumlah fitur:", X.shape[1])
X.columns.tolist()

Jumlah fitur: 31

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 'COURSE ID']

# Split data

In [ ]:


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print("Train:", X_train.shape, " Test:", X_test.shape)

Train: (116, 31)  Test: (29, 31)

# Decision Tree

In [ ]:
dt = DecisionTreeClassifier(
    criterion='gini',
    max_depth=3,
    class_weight=None,
    random_state=42
)

dt.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [ ]:
y_pred = dt.predict(X_test)

acc = accuracy_score(y_test, y_pred)
f1_macro = f1_score(y_test, y_pred, average='macro')

print(f"Accuracy   : {acc:.3f}")
print(f"F1-macro   : {f1_macro:.3f}")
print()
print(classification_report(y_test, y_pred))

Accuracy   : 0.276
F1-macro   : 0.157

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.29      0.57      0.38         7
           2       0.50      0.60      0.55         5
           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00         3
           7       0.33      0.33      0.33         3

    accuracy                           0.28        29
   macro avg       0.14      0.19      0.16        29
weighted avg       0.19      0.28      0.22        29

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Random Forest

In [ ]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=3,
    min_samples_leaf=5,
    class_weight=None,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, min_samples_leaf=5, n_estimators=200,
                       random_state=42)

In [ ]:
y_pred_rf = rf.predict(X_test)

acc_rf = accuracy_score(y_test, y_pred_rf)
f1_macro_rf = f1_score(y_test, y_pred_rf, average='macro')

print(f"Accuracy   : {acc_rf:.3f}")
print(f"F1-macro   : {f1_macro_rf:.3f}")
print()
print(classification_report(y_test, y_pred_rf, zero_division=0))

Accuracy   : 0.310
F1-macro   : 0.161

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.29      1.00      0.45         7
           2       0.00      0.00      0.00         5
           3       0.50      0.25      0.33         4
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00         3
           7       1.00      0.33      0.50         3

    accuracy                           0.31        29
   macro avg       0.22      0.20      0.16        29
weighted avg       0.24      0.31      0.21        29

# Naive bayess

In [ ]:
encoder = OrdinalEncoder()
encoder.fit(X)

X_train_enc = encoder.transform(X_train)
X_test_enc = encoder.transform(X_test)

print("Train encoded:", X_train_enc.shape, " Test encoded:", X_test_enc.shape)

Train encoded: (116, 31)  Test encoded: (29, 31)

In [ ]:
nb = CategoricalNB()
nb.fit(X_train_enc, y_train)

CategoricalNB()

In [ ]:
y_pred_nb = nb.predict(X_test_enc)

acc_nb = accuracy_score(y_test, y_pred_nb)
f1_macro_nb = f1_score(y_test, y_pred_nb, average='macro')

print(f"Accuracy   : {acc_nb:.3f}")
print(f"F1-macro   : {f1_macro_nb:.3f}")
print()
print(classification_report(y_test, y_pred_nb, zero_division=0))

Accuracy   : 0.448
F1-macro   : 0.420

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.42      0.71      0.53         7
           2       0.50      0.20      0.29         5
           3       0.43      0.75      0.55         4
           4       0.00      0.00      0.00         2
           5       1.00      0.33      0.50         3
           6       0.33      0.33      0.33         3
           7       1.00      0.33      0.50         3

    accuracy                           0.45        29
   macro avg       0.58      0.40      0.42        29
weighted avg       0.56      0.45      0.44        29